[phases.setup]
nixPkgs = ['nodejs', 'yarn']

[phases.install]
cmds = ['yarn install']

[phases.build]
cmds = ['yarn build']

[start]
cmd = 'yarn preview'

[variables]
NODE_ENV = 'production'
VITE_REDIS_HOST = 'site_site'
VITE_REDIS_PORT = '6379'
VITE_REDIS_USERNAME = 'default'
VITE_REDIS_PASSWORD = '435ccfa1e2e01233a342' 